### ISSUE TITLE
Missing a range of numbers 

### ISSUE THREAD

**Issue by graciemcguire** [learn-co-curriculum/phase-1-control-flow-lab#6]
### Canvas Link

https://flatiron-staff.slack.com/archives/CR07X87PC/p1648592593158789?thread_ts=1648592229.650839&cid=CR07X87PC

### Concern

Flagged by @mlgvla in Slack:

Hi - I just helped a student on the current phase-1-control-flow-lab, and noticed that it's missing a range of numbers.  This is the current code:
```
function scuberGreetingForFeet (feet) {
  if (feet <= 400) {
    return 'This one is on me!';
  } else if (1999 < feet && feet < 2500) {
    return "I will gladly take your thirty bucks.";
  } else {
    return "No can do.";
  }
}
```
There is no condition in for numbers between 400 and 2000.  If I were to pass in, say, 500, the it will say "No can do."  I don't know, I certainly would  take a rider who wanted to travel between 400 and 2000 feet - charge them, maybe $20 or something (based on these rates!)
Would it be possible to add this range to the deliverables and put in a testing condition for it?  It might make the logic flow better to a student.

**Comment by AlveeM** [comment]
I've made the changes to both the master and solution branches.
